### ISSUE TITLE
Error generating Nothing item in shop

### ISSUE THREAD

**Issue by fenhl** [fenhl/OoT-Randomizer#20]
If the randomizer attempts to place a Nothing item (from https://github.com/OoTRandomizer/OoT-Randomizer/pull/2069) into a shop, it causes the following exception:

```
can't convert negative int to unsigned
Traceback (most recent call last):
  File "[path]\fenhl_OoT-Randomizer\OoTRandomizer.py", line 57, in start
    main(settings)
  File "[path]\fenhl_OoT-Randomizer\Main.py", line 58, in main
    patch_and_output(base_settings, spoiler, rom)
  File "[path]\fenhl_OoT-Randomizer\Main.py", line 327, in patch_and_output
    patch_cosmetics_log = prepare_rom(spoiler, world, rom, settings, rng_state, restore_rom)
  File "[path]\fenhl_OoT-Randomizer\Main.py", line 207, in prepare_rom
    patch_rom(spoiler, world, rom)
  File "[path]\fenhl_OoT-Randomizer\Patches.py", line 2601, in patch_rom
    write_shop_items(rom, shop_item_file.start + 0x1DEC, shop_items)
  File "[path]\fenhl_OoT-Randomizer\Messages.py", line 1053, in write_shop_items
    s.write(rom, shop_table_address, s.index)
  File "[path]\fenhl_OoT-Randomizer\Messages.py", line 1023, in write
    data += int_to_bytes(self.model, 2)
  File "[path]\fenhl_OoT-Randomizer\Messages.py", line 576, in int_to_bytes
    return int.to_bytes(num, width, byteorder='big', signed=signed)
OverflowError: can't convert negative int to unsigned
```

The following plando can be used to reproduce this issue:

```json
{
    "settings": {
        "shopsanity": "4",
        "shuffle_pots": "all",
        "shuffle_empty_pots": true
    },
    "locations": {
        "KF Shop Item 5": "Nothing"
    }
}
```

The issue does not reproduce on the PR branch for https://github.com/OoTRandomizer/OoT-Randomizer/pull/2069.

**Comment by fenhl** [comment]
Should be fixed in 0581b833b.
